#!/usr/bin/env bash
# (Re)generate the platform-tagged fixture contracts under kimon/env/fixtures_ls6/
# from the currently-present fixtures, and record the expected manifest/contract
# hashes the block run scripts check. Run after prepare_fixtures.sh.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly REPO="${REPO_ROOT:-$(cd "${SCRIPT_DIR}/../.." && pwd)}"
readonly FZ="${REPO}/fhe/gpu_real_scheme_b"
readonly OUT="${SCRIPT_DIR}/fixtures_ls6"
readonly BLK="${REPO}/checkpoints/fhe_exports/gsr_pos0_block0_t103_d63353abdc1a_52d046d1fcf0"
readonly MUL="${REPO}/checkpoints/fhe_exports/gsr_pos0_multiblock_t103_d63353abdc1a_52d046d1fcf0"
mkdir -p "${OUT}"

gen() { # frozen_contract fixture_dir out_contract
  awk '{print $2}' "$1" | ( cd "$2" && xargs sha256sum ) > "$3"
  echo "[gen] $3 ($(wc -l < "$3") files)"
}
gen "${FZ}/fixture_t103.sha256"                 "${BLK}" "${OUT}/fixture_t103.sha256"
gen "${FZ}/fixture_t103_qkvshard.sha256"        "${BLK}" "${OUT}/fixture_t103_qkvshard.sha256"
gen "${FZ}/fixture_all_blocks_head_t103.sha256" "${MUL}" "${OUT}/fixture_all_blocks_head_t103.sha256"

{
  echo "# Platform-tagged expected hashes (TACC ls6). Generated by refresh_platform_contracts.sh."
  echo "# Consumed by kimon/env/common.sh (run-script KIMON_* overrides) and"
  echo "# kimon/env/build_binaries.sh (compile-time KIMON_PIN_* binary overrides)."
  echo "KIMON_LS6_MANIFEST_BLOCK=$(sha256sum "${BLK}/manifest.json" | cut -d' ' -f1)"
  echo "KIMON_LS6_CONTRACT_T103=$(sha256sum "${OUT}/fixture_t103.sha256" | cut -d' ' -f1)"
  echo "KIMON_LS6_CONTRACT_QKVSHARD=$(sha256sum "${OUT}/fixture_t103_qkvshard.sha256" | cut -d' ' -f1)"
  echo "KIMON_LS6_MANIFEST_MULTIBLOCK=$(sha256sum "${MUL}/manifest.json" | cut -d' ' -f1)"
  echo "KIMON_LS6_CONTRACT_ALLBLOCKS=$(sha256sum "${OUT}/fixture_all_blocks_head_t103.sha256" | cut -d' ' -f1)"
} > "${OUT}/expected.env"
echo "[ok] wrote ${OUT}/expected.env"
cat "${OUT}/expected.env"
