#!/usr/bin/env python3
"""Derive the real full-gate rotation contract from the frozen implementation.

This intentionally reads ``fhe/gpu_real/src/real_dnagpt_fides.cpp`` instead of
maintaining a second hand-written key list.  It fails closed if the source no
longer contains the algorithmic contract this module knows how to reproduce.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

MEASURED_FULL_ROTATION_COUNT = 63


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _constant(source: str, name: str) -> int:
    match = re.search(
        rf"constexpr\s+(?:std::size_t|std::uint32_t)\s+{re.escape(name)}\s*=\s*"
        r"([0-9]+)\s*;",
        source,
    )
    if match:
        return int(match.group(1))
    if name == "SLOTS" and re.search(
        r"constexpr\s+std::size_t\s+SLOTS\s*=\s*COPIES\s*\*\s*PACK_WIDTH\s*;",
        source,
    ):
        return _constant(source, "COPIES") * _constant(source, "PACK_WIDTH")
    if name == "BSGS_N2" and re.search(
        r"constexpr\s+std::size_t\s+BSGS_N2\s*=\s*"
        r"PACK_WIDTH\s*/\s*BSGS_N1\s*;",
        source,
    ):
        return _constant(source, "PACK_WIDTH") // _constant(source, "BSGS_N1")
    raise ValueError(f"missing integer constant {name}")


def _require_algorithm(source: str) -> None:
    """Reject source drift that could change the required key set."""

    required_patterns = (
        r"int\s+canonical_rotation\s*\(\s*std::int64_t\s+index\s*\)",
        r"constexpr\s+int\s+base_step\s*=\s*4\s*;",
        r"step\s*=\s*1\s*;\s*step\s*<\s*count\s*;\s*step\s*\*=\s*base_step",
        r"multiple\s*=\s*1\s*;\s*multiple\s*<\s*base_step",
        r"baby\s*=\s*1\s*;\s*baby\s*<\s*BSGS_N1",
        r"giant\s*=\s*1\s*;\s*giant\s*<\s*BSGS_N2",
        r"indices\.insert\s*\(\s*static_cast<int>\s*\(\s*BSGS_N1\s*\*\s*giant",
        r"add_accumulate_keys\s*\(\s*indices\s*,"
        r"\s*static_cast<int>\s*\(\s*PACK_WIDTH\s*\)\s*,\s*1\s*\)",
        r"indices\.erase\s*\(\s*0\s*\)",
    )
    missing = [
        pattern for pattern in required_patterns if not re.search(pattern, source)
    ]
    if missing:
        raise ValueError(
            "real-gate rotation algorithm changed; refusing to infer keys: "
            + ", ".join(missing)
        )


def derive(source_path: Path) -> dict:
    source_path = source_path.resolve()
    source = source_path.read_text(encoding="utf-8")
    _require_algorithm(source)

    pack_width = _constant(source, "PACK_WIDTH")
    slots = _constant(source, "SLOTS")
    bsgs_n1 = _constant(source, "BSGS_N1")
    bsgs_n2 = _constant(source, "BSGS_N2")
    if bsgs_n1 * bsgs_n2 != pack_width:
        raise ValueError("BSGS_N1 * BSGS_N2 no longer equals PACK_WIDTH")

    def canonical(index: int) -> int:
        result = index % slots
        if result > slots // 2:
            result -= slots
        return result

    rotations: set[int] = set(range(1, bsgs_n1))
    rotations.update(bsgs_n1 * giant for giant in range(1, bsgs_n2))

    base_step = 4
    step = 1
    while step < pack_width:
        for multiple in range(1, base_step):
            if step * multiple < pack_width:
                rotations.add(canonical(step * multiple))
        step *= base_step
    rotations.discard(0)
    ordered = sorted(rotations)

    if len(ordered) != MEASURED_FULL_ROTATION_COUNT:
        raise ValueError(
            "derived full-gate vector has "
            f"{len(ordered)} keys, expected measured count "
            f"{MEASURED_FULL_ROTATION_COUNT}"
        )
    return {
        "gate": "full",
        "count": len(ordered),
        "steps": ordered,
        "pack_width": pack_width,
        "slots": slots,
        "bsgs_n1": bsgs_n1,
        "bsgs_n2": bsgs_n2,
        "real_source": str(source_path),
        "real_source_sha256": sha256(source_path),
        "derivation": (
            "required_rotation_keys(full): BSGS baby + giant rotations union "
            "base-4 AccumulateSum(PACK_WIDTH, stride=1), canonicalized and sorted"
        ),
        "evidence_note": (
            "63 is the frozen executable/measured attention-gate count; an "
            "earlier 65-key hand estimate is superseded"
        ),
    }


def cpp_text(contract: dict) -> str:
    steps = ", ".join(str(step) for step in contract["steps"])
    return f"""// Generated by rotation_contract.py. Do not edit.
#pragma once

#include <array>
#include <cstdint>
#include <string_view>

namespace dnagpt_cache_contract {{
inline constexpr std::array<std::int32_t, {contract["count"]}> kFullRotations = {{
    {steps}
}};
inline constexpr std::string_view kRealSourceSha256 =
    "{contract["real_source_sha256"]}";
}}  // namespace dnagpt_cache_contract
"""


def emit_cpp(contract: dict, output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(cpp_text(contract), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--emit-cpp", type=Path)
    parser.add_argument("--check-cpp", type=Path)
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    contract = derive(args.source)
    if args.emit_cpp:
        emit_cpp(contract, args.emit_cpp)
    if args.check_cpp:
        actual = args.check_cpp.read_text(encoding="utf-8")
        expected = cpp_text(contract)
        if actual != expected:
            raise SystemExit(
                "committed rotation header drifted; regenerate it with "
                "--emit-cpp and review the real-gate change"
            )
        print(f"ROTATION_HEADER_CHECK_PASS keys={contract['count']}")
    if args.json or (not args.emit_cpp and not args.check_cpp):
        print(json.dumps(contract, indent=2))


if __name__ == "__main__":
    main()
