// Generated by rotation_contract.py. Do not edit.
#pragma once

#include <array>
#include <cstdint>
#include <string_view>

namespace dnagpt_cache_contract {
inline constexpr std::array<std::int32_t, 63> kFullRotations = {
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 48, 64, 96, 128, 160, 192, 224, 256, 288, 320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992
};
inline constexpr std::string_view kRealSourceSha256 =
    "6fd345268f5715499104b0a47a64c4ce01048a0ab6c7732f94b5f517d480381a";
}  // namespace dnagpt_cache_contract
